#!/usr/bin/sh

bspc monitor HDMI-1 -d 1 2 3 4
bspc monitor eDP-1 -d 5 6 7

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sxhkd &
feh --bg-fill /home/castanho/wallpaper.png &
$HOME/.config/polybar/launcher.sh &
$HOME/.config/xrandr/launcher.sh &
picom -f &
dunst &
wmname LG3D &
copyq &
bspc desktop Desktop --remove 
